version: 2


jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.4.0
#      - image: selenium/standalone-firefox:3.4.0

    steps:
      - checkout


      - run:
          name: Checkout master
          command: |
            git fetch --all
            git checkout master
            git reset --hard origin/master
            git checkout $CIRCLE_BRANCH


      - restore_cache:
          key: deps-{{ checksum "yarn.lock" }}


      - run: yarn install --pure-lockfile


      - save_cache:
          key: deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules


      - run:
          name: Prepublush
          command: yarn lerna run prepublish


      - run:
          name: Lint Root
          command: yarn lint


      - run:
          name: Lint
          command: yarn lerna run lint --parallel --stream --no-bail


      - run:
          name: Test
          command: yarn lerna run test --parallel --stream --no-bail


      - run:
          name: Pub
          command: yarn lerna run pub --parallel --stream --no-bail


#      - run:
#          name: End to end tests
#          command: |
#            export DOCKER_IP=$(ifconfig | grep "inet addr:" | grep "Bcast:0.0.0.0" | cut -d: -f2 | awk '{ print $1}')
#            yarn lerna run e2e --parallel --stream --no-bail
